import '../globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// call function conditional test
// function CheckIfRight(){
//   return false
// }

export default function RootLayout({ children, right, left ,center}) {
  // const isRight = CheckIfRight()
  return (
    <html lang="en">
      <body>
        <div className='grid grid-cols-3'>
          {left}
          {center}
          {right}

        </div>
        {children}
      </body>
    </html>
  )
}
