
import "../globals.css"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function AuthLayout({ children }) {
    return (
        <html lang="en">
            <body >
                <header>
                    <h1>HI</h1>
                </header>
                {children}
            </body>
        </html>
    )
}